services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: telegrambot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  telegrambot:
    container_name: telegrambot_container
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - TelegramBot__Token= your_telegram_bot_token #${TELEGRAM_BOT_TOKEN}
      - Sftp__Password=${SFTP_PASSWORD}
      - ConnectionStrings__PostgresDb=Host=db;Port=5432;Database=telegrambot;Username=admin;Password=your_password   # ${POSTGRES_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  postgres_data:
